[deps]
BDF = "0f5c7595-fa0c-55c8-9031-265ea63f34cf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"

[compat]
BDF = "0.5"
CSV = "0.8"
DSP = "0.7"
DataDeps = "0.7"
DataFrames = "1.2"
DisplayAs = "0.1"
Distances = "0.10"
Distributions = "0.21 - 0.25"
Documenter = "0.27"
FFTW = "1"
Glob = "1"
MAT = "0.10"
Plots = "1"
Query = "1"
StatsPlots = "0.14"
Unitful = "1"
julia = "1.4"
